// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBygLbCm0F_f3_TUIEpFO1zak9yKiksnp0',
    appId: '1:836287880326:web:4d18b4e45e4cf493fc8507',
    messagingSenderId: '836287880326',
    projectId: 'flutter-firebase-app-c5daf',
    authDomain: 'flutter-firebase-app-c5daf.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-c5daf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmw__JLdN4WTEqgFZZKtbQdw6_A49a8Io',
    appId: '1:836287880326:android:01c99c6abcf7ddc0fc8507',
    messagingSenderId: '836287880326',
    projectId: 'flutter-firebase-app-c5daf',
    storageBucket: 'flutter-firebase-app-c5daf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhEG5vPuVEAZb7BdTxfks9qJy5oeU5kWw',
    appId: '1:836287880326:ios:854d4eaf6dcb174cfc8507',
    messagingSenderId: '836287880326',
    projectId: 'flutter-firebase-app-c5daf',
    storageBucket: 'flutter-firebase-app-c5daf.appspot.com',
    iosClientId: '836287880326-dgsopup8jnr7usb3qoofhod07t4frakj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhEG5vPuVEAZb7BdTxfks9qJy5oeU5kWw',
    appId: '1:836287880326:ios:854d4eaf6dcb174cfc8507',
    messagingSenderId: '836287880326',
    projectId: 'flutter-firebase-app-c5daf',
    storageBucket: 'flutter-firebase-app-c5daf.appspot.com',
    iosClientId: '836287880326-dgsopup8jnr7usb3qoofhod07t4frakj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );
}
